language: python
dist: xenial
python:
  - "2.7"
  
addons:
  postgresql: "9.4"
  
install:
  - export BOTO_CONFIG=/dev/null
  - python setup.py install
  - pip install -r dev-requirements.txt -r requirements.txt
script: "py.test -v"
