[metadata]
name = cdisutils
description = Miscellaneous utilities useful for interaction with CTDS systems.
long_description = file: README.md
long_description_content_type = text/markdown
author = Gdc feature team
author_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
maintainer = GDC Feature Team
maintainer_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
license = Apache Software License 2.0
license_files = LICENSE
url = https://github.com/NCI-GDC/cdisutils
keywords = Genomic Data Commons, botomanager
classifiers =
    License :: OSI Approved :: Apache Software License
    Topic :: Software Development :: Libraries :: Python Modules
    Programming Language :: Python
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
zip_safe = True
packages = find_namespace:
package_dir =
    =src
python_requires = >=3.7
include_package_data = True
install_requires =
    boto3
    python-dateutil
    requests
    urllib3

[options.packages.find]
where = src

[options.package_data]
gdcdictionary =
    schemas/*.yaml
    schemas/projects/*.yaml

[options.extras_require]
dbgap =
    gdcdatamodel2
    xmltodict>=0.9
dev =
    coverage[toml]
    moto>=4.1
    pytest>=6
    pytest-cov
    flask>=2.0
    flask_cors>=3.0
excel =
    openpyxl>=2.4
nova =
    python-novaclient>=3.2
